// <auto-generated />
namespace IdSrv.Migrations.UserDBConfiguration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Anotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Anotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201603071120320_Anotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
